name: PHP Composer

on:
  push:
    branches: [ master ]

jobs:
  build:
  
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: php -d allow_url_fopen=On ~/composer validate --strict
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: php -d allow_url_fopen=On ~/composer install --prefer-dist --no-progress
    - name: Load db config
      run: echo $DB_CONFIG >> db.json
      shell: bash
      env:
        DB_CONFIG : ${{ secrets.DB_CONFIG }}

    # TODO
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    # - name: Run test suite
    #   run: composer run-script test
