name: PHP Composer

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Check PHP syntax errors
      uses: overtrue/phplint@7.4
      with:
        path: .
    - name: Psalm
      uses: docker://vimeo/psalm-github-actions
      with:
        composer_require_dev: true

  build:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: php -d allow_url_fopen=On ~/composer install --no-dev --prefer-dist --no-progress
    - name: Install bower
      run: npm install bower
    - name: Install leaflet
      run: bower install leaflet
    - name: Install d3
      run: bower install d3
    - name: Install c3
      run: bower install c3
    - name: Load db config
      run: echo $DB_CONFIG >> db.json
      shell: bash
      env:
        DB_CONFIG : ${{ secrets.DB_CONFIG }}